### PR TITLE
add option to filter names of nuget packages

### PR DESCRIPTION
**Pull request by jepperc**
Finally got to look into my suggestion in Issue #55 .. really simple fix actually :)
Hope it's useable.

### CODE REVIEW

**Comment by jerriep** [comment]
@jepperc Thank you for this. I think `filter` can be ambiguous. The name does not say whether it includes or excludes packages that conform to the filter.

It would be more flexible and unambiguous if you instead provide two different ones named `include` and `exclude` which includes or excludes packages based on the values provided.

Also, I would make both of those multi-valued options, so one can specify multiple `include` or `exclude` options.

Hope this makes sense?

**Comment by jerriep** [comment]
@jepperc Just following up on this. Are you planning to still proceed with this PR and look at the feedback I gave?

**Comment by jepperc** [comment]
Hey! Sorry, i've been on paternity leave.

My 2 cents:
I thought the single "--filter" style would be like "dotnet test".. so to keep it in line with that, I would prefer that.
But I just found out that "dotnet test --filter sometest" is a lot more complicated, since it supports all kinds of notations, which I don't think is worth implementing. So I guess your suggestion keeps the most simple implementation, with most flexibility?

**Comment by jerriep** [comment]
Hmm, yeah it may be worth it to use a single `--filter` option if we can somehow allow a way for the user to specify logic operators to indicate if a particular filter should include or exclude.

Let's just sit on this one for a few more days. I'll sleep on it and maybe some idea will formulate itself in my mind :)

**Comment by jepperc** [comment]
Hey! So, i'm back and in need of this feature again :D
Would you accept if I change the implementation to --includefilter and --excludefilter?

**Comment by jerriep** [comment]
Yeah, sure. You can name them `--include` or `--exclude`

**Comment by jerriep** [comment]
Great stuff, thanks for the contribution @jepperc

**Pull request merged**
