### PR TITLE
Add option to generate a JSON report

### PR DESCRIPTION
**Pull request by patros**
For issue #57 

I went with...
- -oj|--output-json as the command line option as I figured other formats might follow. i.e. -ot|--output-text, -ox|--output-xml, etc
- opt in member serialisation for `Project` so new properties don't get automatically added to the json output unintentionally

Example output...

```json
{
  "Projects": [
    {
      "Sources": [
        "https://api.nuget.org/v3/index.json"
      ],
      "TargetFrameworks": [
        {
          "Dependencies": [
            {
              "Name": "NETStandard.Library",
              "ResolvedVersion": "2.0.3",
              "LatestVersion": null,
              "UpgradeSeverity": null
            },
            {
              "Name": "Newtonsoft.Json",
              "ResolvedVersion": "11.0.2",
              "LatestVersion": "11.0.2",
              "UpgradeSeverity": "None"
            }
          ],
          "Name": ".NETStandard,Version=v2.0"
        }
      ],
      "Name": "Patros.AuthenticatedHttpClient.Basic",
      "FilePath": "/home/patrick/OneDrive Personal/Projects/AuthenticatedHttpClient/Patros.AuthenticatedHttpClient.Basic/Patros.AuthenticatedHttpClient.Basic.csproj"
    },
    {
      "Sources": [
        "https://api.nuget.org/v3/index.json"
      ],
      "TargetFrameworks": [
        {
          "Dependencies": [
            {
              "Name": "Microsoft.IdentityModel.Clients.ActiveDirectory",
              "ResolvedVersion": "3.19.8",
              "LatestVersion": "4.3.0",
              "UpgradeSeverity": "Major"
            },
            {
              "Name": "NETStandard.Library",
              "ResolvedVersion": "2.0.3",
              "LatestVersion": null,
              "UpgradeSeverity": null
            }
          ],
          "Name": ".NETStandard,Version=v2.0"
        }
      ],
      "Name": "Patros.AuthenticatedHttpClient.AzureAd",
      "FilePath": "/home/patrick/Personal Projects/AuthenticatedHttpClient/Patros.AuthenticatedHttpClient.AzureAd/Patros.AuthenticatedHttpClient.AzureAd.csproj"
    },
    {
      "Sources": [
        "https://api.nuget.org/v3/index.json"
      ],
      "TargetFrameworks": [
        {
          "Dependencies": [
            {
              "Name": "Microsoft.Azure.Services.AppAuthentication",
              "ResolvedVersion": "1.0.3",
              "LatestVersion": "1.0.3",
              "UpgradeSeverity": "None"
            },
            {
              "Name": "NETStandard.Library",
              "ResolvedVersion": "2.0.3",
              "LatestVersion": null,
              "UpgradeSeverity": null
            }
          ],
          "Name": ".NETStandard,Version=v2.0"
        }
      ],
      "Name": "Patros.AuthenticatedHttpClient.AzureAppServiceManagedIdentity",
      "FilePath": "/home/patrick/Personal Projects/AuthenticatedHttpClient/Patros.AuthenticatedHttpClient.AzureAppServiceManagedIdentity/Patros.AuthenticatedHttpClient.AzureAppServiceManagedIdentity.csproj"
    },
    {
      "Sources": [
        "https://api.nuget.org/v3/index.json"
      ],
      "TargetFrameworks": [
        {
          "Dependencies": [
            {
              "Name": "Microsoft.NET.Test.Sdk",
              "ResolvedVersion": "15.8.0",
              "LatestVersion": "15.9.0",
              "UpgradeSeverity": "Minor"
            },
            {
              "Name": "Microsoft.NETCore.App",
              "ResolvedVersion": "2.1.0",
              "LatestVersion": null,
              "UpgradeSeverity": null
            },
            {
              "Name": "xunit",
              "ResolvedVersion": "2.3.1",
              "LatestVersion": "2.4.1",
              "UpgradeSeverity": "Minor"
            },
            {
              "Name": "xunit.runner.visualstudio",
              "ResolvedVersion": "2.3.1",
              "LatestVersion": "2.4.1",
              "UpgradeSeverity": "Minor"
            }
          ],
          "Name": ".NETCoreApp,Version=v2.1"
        }
      ],
      "Name": "Patros.AuthenticatedHttpClient.Basic.Tests",
      "FilePath": "/home/patrick/Personal Projects/AuthenticatedHttpClient/Patros.AuthenticatedHttpClient.Basic.Tests/Patros.AuthenticatedHttpClient.Basic.Tests.csproj"
    },
    {
      "Sources": [
        "https://api.nuget.org/v3/index.json"
      ],
      "TargetFrameworks": [
        {
          "Dependencies": [
            {
              "Name": "NETStandard.Library",
              "ResolvedVersion": "2.0.3",
              "LatestVersion": null,
              "UpgradeSeverity": null
            },
            {
              "Name": "Newtonsoft.Json",
              "ResolvedVersion": "11.0.2",
              "LatestVersion": "11.0.2",
              "UpgradeSeverity": "None"
            }
          ],
          "Name": ".NETStandard,Version=v2.0"
        }
      ],
      "Name": "Patros.AuthenticatedHttpClient.Basic",
      "FilePath": "/home/patrick/Personal Projects/AuthenticatedHttpClient/Patros.AuthenticatedHttpClient.Basic/Patros.AuthenticatedHttpClient.Basic.csproj"
    }
  ]
}
```

### CODE REVIEW

**Comment by jerriep** [comment]
@patros This is great thanks. I will have time to review properly later, but for now just a few comments:

1. I think it would be better to split this into two options: A `-o|--output` option to specify the name of the file and then a '-of|--output-format` to specify the format. This can be one of `json`, `csv` etc...
2. The NuGet sources listed in the `Sources` node can sometimes contain sensitive information. I think it is better to exclude this.
3. Maybe change the ordering of the nodes for readability. Put them in the order `Name`, `FilePath`, `TargetFrameworks`. For the `TargetFramework` node, you can put its child nodes in the order `Name`, `Dependencies`. You can use `[JsonProperty(Order = n)]` for this.

**Comment by patros** [comment]
Yeah, most people will probably only want one output format. And good catch on the Sources. I'll try to get onto the changes tonight.

**Comment by patros** [comment]
@jerriep I've made the above changes although I left out --output-format for now. I also specified the json property order for dependency nodes to make it clear the ordering is intentional.

**Comment by patros** [comment]
New output...
```
{
  "Projects": [
    {
      "Name": "Patros.AuthenticatedHttpClient.Basic",
      "FilePath": "/home/patrick/OneDrive Personal/Projects/AuthenticatedHttpClient/Patros.AuthenticatedHttpClient.Basic/Patros.AuthenticatedHttpClient.Basic.csproj",
      "TargetFrameworks": [
        {
          "Name": ".NETStandard,Version=v2.0",
          "Dependencies": [
            {
              "Name": "NETStandard.Library",
              "ResolvedVersion": "2.0.3",
              "LatestVersion": null,
              "UpgradeSeverity": null
            },
            {
              "Name": "Newtonsoft.Json",
              "ResolvedVersion": "11.0.2",
              "LatestVersion": "11.0.2",
              "UpgradeSeverity": "None"
            }
          ]
        }
      ]
    },
    {
      "Name": "Patros.AuthenticatedHttpClient.AzureAd",
      "FilePath": "/home/patrick/Personal Projects/AuthenticatedHttpClient/Patros.AuthenticatedHttpClient.AzureAd/Patros.AuthenticatedHttpClient.AzureAd.csproj",
      "TargetFrameworks": [
        {
          "Name": ".NETStandard,Version=v2.0",
          "Dependencies": [
            {
              "Name": "Microsoft.IdentityModel.Clients.ActiveDirectory",
              "ResolvedVersion": "3.19.8",
              "LatestVersion": "4.3.0",
              "UpgradeSeverity": "Major"
            },
            {
              "Name": "NETStandard.Library",
              "ResolvedVersion": "2.0.3",
              "LatestVersion": null,
              "UpgradeSeverity": null
            }
          ]
        }
      ]
    },

...
```

**Comment by jerriep** [comment]
Great, now I also know about `[JsonObject(MemberSerialization.OptIn)]` 😄 

I have not had chance to test properly, but I looked it over and it looks fine. I am going ahead and merge, so it will give you opportunity to proceed #103

Thank you!

**Comment by patros** [comment]
@jerriep you're welcome. I love the knowledge sharing opportunity with open source projects. I'm already looking at incorporating System.IO.Abstractions into my projects :)

**Pull request merged**
