### PR TITLE
add support for .net core 3.0

### PR DESCRIPTION
**Pull request by ahryshchanka**

### CODE REVIEW

**Comment by ahryshchanka** [comment]
Hi @jerriep

Please merge first #226 , it fix CI and after it current PR have to be merget without problem

**Comment by jerriep** [comment]
Same are for the other PR, please remove the changes to the `*.cs` files. The only changes I believe are required are to the `*.csproj` files

**Comment by ahryshchanka** [comment]
@jerriep you are right. Re-implemented.

But please merge first #226 because build broken and I can't pass CI gate. After merge #226 we will have chnages only in `*.csproj` + new line in `appveyor.yml`

**Comment by jerriep** [comment]
@ahryshchanka Thanks. I have merged the other PR as it is a straight-forward change.

For this one I need to make the time to test and see whether the multi-targeting works correctly on machines that only have 2.1 or 3.0 installed. For this, I will likely only find time in December, so this PR may need to sit for a few weeks.

Did you by any chance come across any sort of documentation or blog post discussing multi targeting of global tools?

**Comment by ahryshchanka** [comment]
@jerriep 

It is sad, but can't find a lot of explanations about multi-target .net core framework and `dotnet` tools in one topic, only [one](https://johan-v-r.github.io/2018/09/05/NET-Core-Global-Tools-Configuration/).
All that were used:
- tests other tools with multi-target on my macbook, [PR](https://github.com/solidsloth/dotnet-gitignore/pull/14)
- example in [other-1](https://github.com/jonathanpeppers/boots/blob/8b8765a0725785fdf8fc996b22770a3009605b74/Boots/Boots.csproj#L5) , [other-2](https://github.com/fszlin/certes/blob/f9980d2d7077e3b371f6fc156077f76eaecf2dd0/src/Certes.Cli/Certes.Cli.csproj#L6) dotnet tools
- investigation hot to multi-target tool installed on my win pc 
image
- `framework` parameter in [topic](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-tool-install.md) and [reference](https://github.com/dotnet/docs/blob/master/docs/standard/frameworks.md) to other topic with explanations about multi-target feature

based on all above it have to work.

**Comment by jerriep** [comment]
@ahryshchanka OK, cool. Thanks for this.

I'll test as soon as I get a chance and then merge this PR, but it may be a couple of weeks before I get to it as I am pushing to get some client work finished before the end of the year

**Comment by jerriep** [comment]
Thanks for this @ahryshchanka 

I have now released a new version on NuGet

**Pull request merged**
