### PR TITLE
Performance improvement PR for #143

### PR DESCRIPTION
**Pull request by batzen**
As described in #143 this PR massively improves the performance while gathering outdated projects by reducing the amout of restores and doing things in parallel.

### CODE REVIEW

**Comment by batzen** [comment]
Will work on fixing the test failures.

**Comment by jerriep** [comment]
Thank you @batzen. Please ping me with an @ mention once you have addressed the failing tests, then I will look at it.

**Comment by batzen** [comment]
@jerriep I fixed the tests. A few are now obsolete and i removed them as i switched to restoring the whole solution instead of getting projects and restoring one by one.

**Comment by jerriep** [comment]
@batzen Wow! You were not exaggerating when you said it is a major speed improvement. It feels almost instantaneous.

Thank you for submitting this and pushing it through despite my relucatance at the time to accept new PRs. This will make life for the users much better

**Comment by cwe1ss** [comment]
I just ran dotnet outdated and thought something was wrong because it was so much faster, so I looked up the changes and found this PR. This is amazing work!!!! thank you very much!!!

**Comment by batzen** [comment]
You are welcome 😊

**Pull request merged**
