### PR TITLE
Add some improvements to code quality

### PR DESCRIPTION
**Pull request by joeltankam**

### CODE REVIEW

**Comment by jerriep** [comment]
@joeltankam Thank you, but some of these formatting changes you made are not necessarily how I prefer it. I will not accept this. I'd rather run Resharper's code cleanup if I have to

**Comment by joeltankam** [comment]
Indeed, some of the formatting changes are a matter of taste. That's why I
did this in many commits, some of them might still be worthy. Some commits
or changed can be reverted at your convenience.

**Comment by joeltankam** [comment]
@jerriep please take a look again, preferably per commit.

**Comment by jerriep** [comment]
@joeltankam I am sorry, I am not going to accept a PR that simply changes the formatting to your preferences. I have VS and Resharper configured to my own preferences. Next time I work on the code, my own settings may once again change this.

I really do not want to discourage you from contributing to open source software, but this is not the way to go about things. Very few projects (whether open or closed source) will appreciate someone blowing through and just changing the formatting to their own personal preferences - especially if it is their first and only contribution ever to said project.

Besides this, I have a major reorganization PR waiting in the wings (#151) that moves a lot of code out into a separate library. If I accepted your PR it will cause major merging conflicts for them. 

BTW in their case, they discussed these changes with me beforehand to ensure that I am open to them. I would like to suggest that you that their approach in the future and discuss it with repository owners before submitting potentially disruptive changes like this.

**Comment by joeltankam** [comment]
@jerriep Once gain, formatting changes are just 1 or 2 of the 14 commits.
Regarding your Re# preferences, a common practice is to version the `*.sln.DotSettings` file (Solution Team-Shared layer).

**Comment by jerriep** [comment]
@joeltankam I have said all I am going to say about this. I will not accept this PR. End of story. Please stop arguing about it.

**Comment by joeltankam** [comment]
@jerriep Ok, great. 
Versioning your Re# settings was more of a recommendation rather than an "argument". 
Also, it's the lack of flexibility that seems weird to me. Automatically closing a PR due to small inconveniences is not a good way of dealing with community in my opinion. There's a reason why we can comment on specific changes or commits.
I perfectly agree that big changes should be discussed before submitting a PR. But I can't see how commits such as "Fix possible 'System.NullReferenceException'" should be included in that category. 
Anyway, I'm not particularly attached to this PR, so at your please. Nice repo 👍
This was preliminary step for a more feature-oriented PR, since there are 70+ warnings in my VS (which probably wouldn't be the case if your settings were versioned).

**Comment by jerriep** [comment]
> This was preliminary step for a more feature-oriented PR,

I would strongly suggest that you learn a lesson from this PR and do not just do the work and open a new PR without discussing it first. Start off by creating an issue and find out whether I would be in fact open to the feature you want to add. (BTW, this is a good rule to follow for **any** projects you want to contribute to)

As things stand at the moment, I am not giving much attention to this tool anymore since you can now do most of what it does by using the built-in `dotnet list package --outdated` command ([see docs](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-list-package))

With that in mind I am fairly unwilling to enhance this tool much further. Also, my priorities are elsewhere at the moment.

**Pull request closed without merging**
