### PR TITLE
Moved core functionality to DotNetOutdated.Core library

### PR DESCRIPTION
**Pull request by GStoob**
This PR moves the core functionality of `DotNet Outdated` into a separate .NET Standard library (`DotnetOutdated.Core`). This allows to embed and use its excelent functions in your own projects without calling manually into the CLI.

I took almost everything over as-is, I added an extra extension method for the `GetValueOrDefault()` method used in some places when retrieving values from a dictionary. This method is not available in .NET Standard 2.0, but will be in .NET Standard 2.1 as far as I know. Then I also added an extra property to the project model for retrieving the current project version when using the `ProjectAnalysisService`.
Services like the `CSV Reporter` are still in the CLI project.

CC @filipw

### CODE REVIEW

**Comment by jerriep** [comment]
Thank you, @GStoob 

I'll see if I can find time this weekend to get this merged and published

**Comment by jerriep** [comment]
@GStoob I did not get around to this the weekend. I am not sure when I will be able to as I have other higher priorities. 

In the interim, I suggest publishing the Core package to your own internal NuGet feed and using that.

**Comment by filipw** [comment]
> In the interim, I suggest publishing the Core package to your own internal NuGet feed and using that.

That's exactly what we've done last week. Once you find some time to get this in, we'll simply switch the source - thanks!

**Comment by jerriep** [comment]
@GStoob @filipw OK guys, v.2.3.0 along with your stand-alone library is now on NuGet. Thanks!

**Pull request merged**
