### PR TITLE
Color only the upgraded part of the version number

### LINKED ISSUE #45: Show what part of the version number has changed
Thanks for an awesome tool!

I think it could be even cooler, if it stole some ideas from e.g. `yarn outdated`. This is my output from there:

image

Note how the different colors indicate whether this is a major, minor or patch update, and makes it clear which components of the version number have changed.

`dotnet outdated` could improve on the current format by showing, e.g. outdated version number part on the currently installed version in red, and the latest version of those parts in blue (and up-to-date packages in green as currently).

What do you think, would this be a good idea? How difficult would it be to implement?

### PR DESCRIPTION
**Pull request by tlycken**
With this update, an upgrade e.g. 2.3.6 -> 3.1.0 will be displayed as before (all red), but 2.3.6 -> 2.5.1 will display only 5.1 in yellow, and 2.3.6 -> 2.3.8 will display only 8 in green.

sample output

This fixes #45.

### CODE REVIEW

**Comment by jerriep** [comment]
@tlycken This is much more complicated than it needs to be. There is already a method which determines the color called `GetUpgradeSeverityColor` which you can keep as-is. 

The only thing you need to is to derermine is which part of the version string to color.  For that, you can use the technique in [this Stackoverflow answer](https://stackoverflow.com/a/4585989)

So it means that the only thing that needs to change is this line of code:
https://github.com/jerriep/dotnet-outdated/blob/87c6c16e8b3993fefc64c09eb922a579d5d14b2c/src/DotNetOutdated/Program.cs#L263

It can be replaced with the following three lines:

```csharp
int index = resolvedVersion.Zip(latestVersion, (c1, c2) => c1 == c2).TakeWhile(b => b).Count() + 1;

console.Write(latestVersion.Substring(0, index - 1));
console.Write(latestVersion.Substring(index - 1), GetUpgradeSeverityColor(dependency.LatestVersion, dependency.ResolvedVersion));
```

That give exactly the same result you have. The only problem with that code is that for pre-releases, it will only highlight the pre-release part that of the version which changed, e.g.

image

So you can use a special case for pre-release version to highlight the entire version number, so the three lines above becomes:

```csharp
if (dependency.LatestVersion.IsPrerelease)
{
    console.Write(latestVersion, GetUpgradeSeverityColor(dependency.LatestVersion, dependency.ResolvedVersion));
}
else
{
    int index = resolvedVersion.Zip(latestVersion, (c1, c2) => c1 == c2).TakeWhile(b => b).Count() + 1;

    console.Write(latestVersion.Substring(0, index - 1));
    console.Write(latestVersion.Substring(index - 1), GetUpgradeSeverityColor(dependency.LatestVersion, dependency.ResolvedVersion));
}
```

**Comment by jerriep** [comment]
Actually, on second thought, there are cases where my approach does not work. Let's take an example where a version is upgraded from `1.11.0` to `1.12.0`. Using my approach, only the last `2.0` part will be colored, but one would want to color the entire bit from the minor version onwards, i.e. `12.0`

Let me look at your PR tomorrow when I have more time. It still seems a bit complicated, but I need to get my head around it.

**Comment by tlycken** [comment]
Well, I probably have a similar bug in my version: if I'm not mistaken, an upgrade from `12.13.1` to `12.13.4` will highlight `3.4`, and not only `4`.

It's quite possible that I've made this more complicated than it needs to be, but part of that is because I wanted to split the determining of upgrade severity from the choosing of color - they were intertwined before, and splitting them is what added most of the new lines of code.

Thanks for the tip on iterating over the version strings, though - I'll see if I can shorten down the `WriteColoredUpgrade` method with that approach!

**Comment by tlycken** [comment]
@jerriep I've pushed a new version, which does simplify quite a lot based on your suggestions.

I started to write some tests to verify that the behavior is correct, but I find it pretty difficult to write tests efficiently against the `IConsole` interface. Do you have any tips for mocking/stubbing it? Are there any mocks/stubs available somewhere already?

**Comment by jerriep** [comment]
Great stuff, thank you @tlycken

**Pull request merged**
